name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install C++ Build Tools
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller darkdetect

      - name: Download Face Predictor Model
        run: curl -L -o shape_predictor_68_face_landmarks.dat https://github.com/italojs/facetracker/raw/master/data/shape_predictor_68_face_landmarks.dat

      - name: The Nuclear Build
        run: |
          $ctk_path = python -c "import customtkinter; import os; print(os.path.dirname(customtkinter.__file__))"
          echo "CustomTkinter path is: $ctk_path"
          pyinstaller --onefile --noconsole `
          --collect-all mediapipe `
          --add-data "$($ctk_path);customtkinter/" `
          --add-data "shape_predictor_68_face_landmarks.dat;." `
          --hidden-import=darkdetect `
          new_ui.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Gesture-Security-System-Final
          path: dist/*.exe
